// Reviewed against the product repositories at the pinned revisions below.
// Keep source availability distinct from the mere presence of an integration.
export const otherApps = [
  {
    slug: "titanskies",
    title: "TitanSkies",
    summary: "Explore wildfire smoke forecasts, air-quality readings, and reported fire context across North America.",
    liveUrl: "https://www.titanskies.com/",
    sourceUrl: "https://github.com/hypertrial/titanskies",
    sourceRevision: "3cf6db94229dc8eb195f4caf662da01eb0e83691",
    sourceEvidenceUrl: "https://github.com/hypertrial/titanskies/blob/3cf6db94229dc8eb195f4caf662da01eb0e83691/shared/data-sources.json",
    reviewedAt: "2026-09-28",
    sourceIntro: "TitanSkies combines two smoke models with preliminary monitoring data and agency-reported wildfire context. Individual inputs can be stale or unavailable; forecasts are not observations or emergency alerts.",
    sources: [
      {
        name: "ECCC FireWork",
        group: "Forecasts",
        role: "Base smoke-concentration forecast for the integrated map.",
        availability: "Configured public WCS forecast; a failed or stale run can retain a dated prior forecast.",
        officialUrl: "https://www.weather.gc.ca/firework/index_e.html",
        coverage: "Canada and adjoining areas covered by the FireWork model.",
        noGuideReason: "A FireWork-specific guide has not passed the Data catalog review.",
      },
      {
        name: "NOAA HRRR-Smoke",
        group: "Forecasts",
        role: "U.S. smoke forecast enhancement where it exceeds the FireWork base.",
        availability: "Configured public GRIB forecast; freshness and fallback are checked per run.",
        officialUrl: "https://rapidrefresh.noaa.gov/hrrr/HRRRsmoke/",
        coverage: "United States model domain.",
        noGuideReason: "A HRRR-Smoke-specific guide has not passed the Data catalog review.",
      },
      {
        name: "EPA AirNow",
        group: "Observations",
        role: "Provider-reported PM2.5 AQI at participating monitors; TitanSkies does not recalculate these AQI values.",
        availability: "Optional: requires AIRNOW_API_KEY. Missing key or provider failure makes this monitor set unavailable or dated.",
        officialUrl: "https://docs.airnowapi.org/webservices",
        coverage: "Participating U.S. monitoring sites.",
        guideId: "airnow-air-quality",
      },
      {
        name: "B.C. ENV air quality",
        group: "Observations",
        role: "Hourly PM2.5 concentrations converted by TitanSkies to U.S. EPA NowCast AQI.",
        availability: "Configured public observation feed; stations and timestamps may be incomplete or stale.",
        officialUrl: "https://www2.gov.bc.ca/gov/content/environment/air-land-water/air/air-quality/current-air-quality-data",
        coverage: "British Columbia stations.",
        noGuideReason: "A guide for this B.C. hourly feed has not passed catalog review.",
      },
      {
        name: "INECC SINAICA",
        group: "Observations",
        role: "Hourly PM2.5 concentrations quality-screened and converted to U.S. EPA NowCast AQI.",
        availability: "Gated by SINAICA_ENABLED; disabled sources and failed reads are reported as unavailable or dated.",
        officialUrl: "https://sinaica.inecc.gob.mx/",
        coverage: "Participating Mexico monitoring stations.",
        noGuideReason: "A SINAICA-specific guide has not passed catalog review.",
      },
      {
        name: "ECCC Air Quality Health Index",
        group: "Observations",
        role: "Canadian AQHI observations, kept on the AQHI scale rather than converted to AQI.",
        availability: "Configured public feed; observations can be missing or stale.",
        officialUrl: "https://weather.gc.ca/airquality/pages/index_e.html",
        coverage: "Participating Canadian stations.",
        noGuideReason: "An AQHI observation guide has not passed catalog review.",
      },
      {
        name: "NIFC WFIGS",
        group: "Wildfire context",
        role: "Agency-reported U.S. wildfire incident points and perimeters; they do not identify a smoke plume's origin.",
        availability: "Configured public service with per-run freshness checks and dated fallback.",
        officialUrl: "https://data-nifc.opendata.arcgis.com/",
        coverage: "United States incidents and perimeters.",
        noGuideReason: "A WFIGS incident-layer guide has not passed catalog review.",
      },
      {
        name: "NRCan CWFIS",
        group: "Wildfire context",
        role: "Agency-reported Canadian wildfire incident points and perimeters.",
        availability: "Configured public service with per-run freshness checks and dated fallback.",
        officialUrl: "https://cwfis.cfs.nrcan.gc.ca/",
        coverage: "Canada incidents and perimeters.",
        noGuideReason: "A CWFIS incident-layer guide has not passed catalog review.",
      },
      {
        name: "Natural Earth oceans and populated places",
        group: "Pinned geography",
        role: "Ocean mask for smoke coverage and city candidates for ranked smoke and AQI results and search.",
        availability: "Pinned 50m ocean and 10m populated-place source artifacts used during the geography build, not a live feed.",
        officialUrl: "https://www.naturalearthdata.com/",
        evidenceUrl: "https://github.com/hypertrial/titanskies/blob/3cf6db94229dc8eb195f4caf662da01eb0e83691/scripts/generate_geo.py",
        coverage: "North America within the generated map and city catalog.",
        noGuideReason: "The existing Natural Earth guide covers 110m country boundaries, not these 50m ocean and 10m populated-place artifacts.",
      },
    ],
  },
  {
    slug: "hyperoptions",
    title: "HyperOptions",
    summary: "Explore Nasdaq-listed covered calls and cash-secured puts with dated market context and stock forecasts.",
    sourceUrl: "https://github.com/hypertrial/hyperoptions",
    sourceRevision: "e23909d37cdf65f40967bc5c4194a8dcda967602",
    sourceEvidenceUrl: "https://github.com/hypertrial/hyperoptions/blob/e23909d37cdf65f40967bc5c4194a8dcda967602/README.md",
    reviewedAt: "2026-09-28",
    sourceIntro: "HyperOptions is a local workstation. Its chain and watch results depend on public market endpoints; some research methods remain unavailable until input rights or evidence qualify. It is not a brokerage or trading recommendation.",
    sources: [
      {
        name: "Nasdaq public market endpoints",
        group: "Market data",
        role: "Listed-stock universe, stock quote, option chains, and completed daily price lows; also cross-checks expiry closes.",
        availability: "Enabled, unofficial public JSON access for personal local use; chain and new watches fail closed if the ticker universe cannot load.",
        officialUrl: "https://www.nasdaq.com/market-activity/stocks",
        evidenceUrl: "https://github.com/hypertrial/hyperoptions/blob/e23909d37cdf65f40967bc5c4194a8dcda967602/backend/src/options_api/nasdaq.py",
        noGuideReason: "No Nasdaq option-chain guide has passed the Data catalog's access and reuse review.",
      },
      {
        name: "Yahoo Finance",
        group: "Market data",
        role: "Completed stock prices for physical forecasts and provisional expiry results, dividend status that gates market-implied odds, and option-chain replacement when Nasdaq coverage is truncated.",
        availability: "Enabled through an unofficial client, with verified local caches. Training on Yahoo-derived histories is gated while rights remain unverified.",
        officialUrl: "https://finance.yahoo.com/",
        evidenceUrl: "https://github.com/hypertrial/hyperoptions/blob/e23909d37cdf65f40967bc5c4194a8dcda967602/docs/source-rights.md",
        noGuideReason: "Automated history and option-quote reuse rights have not qualified for a Data guide.",
      },
      {
        name: "U.S. Treasury interest rates",
        group: "Market data",
        role: "Dated yield curve used as the risk-free rate for option Greeks and market-implied odds.",
        availability: "Configured public XML source; unavailable dates withhold dependent calculations.",
        officialUrl: "https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml",
        evidenceUrl: "https://github.com/hypertrial/hyperoptions/blob/e23909d37cdf65f40967bc5c4194a8dcda967602/backend/src/options_api/market_sources.py",
        noGuideReason: "The existing Treasury auctions guide covers a different data product; yield-curve guide review is pending.",
      },
      {
        name: "SEC EDGAR submissions",
        group: "Research inputs",
        role: "Explicit future earnings-date announcements from selected 8-K exhibits for the gated earnings-jump research method.",
        availability: "Deliberate, contact-identified capture only; it does not run at startup and a filing date alone never enables the model.",
        officialUrl: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        evidenceUrl: "https://github.com/hypertrial/hyperoptions/blob/e23909d37cdf65f40967bc5c4194a8dcda967602/docs/source-rights.md",
        guideId: "sec-edgar-apis",
      },
    ],
  },
  {
    slug: "househunter",
    title: "HouseHunter",
    summary: "Compare U.S. residential hazards and county context with pinned public data and optional private home-cost imports.",
    status: "alpha",
    sourceUrl: "https://github.com/hypertrial/househunter",
    sourceRevision: "eea3dfffb5bd728afff4e63edda27959e7d86f97",
    sourceEvidenceUrl: "https://github.com/hypertrial/househunter/blob/eea3dfffb5bd728afff4e63edda27959e7d86f97/DATA_SOURCES.md",
    reviewedAt: "2026-09-28",
    sourceIntro: "HouseHunter pins source vintages for its local hazard map and county fit tools. Normal runs use verified caches and packaged ranking references; maintainer-only inputs are not live feeds. Home-market history is private, imported only by the user, and never published here.",
    sources: [
      {
        name: "FEMA National Risk Index",
        group: "Core hazard map",
        role: "Separate tract and county building-loss inputs for 17 hazards; HouseHunter derives residential hazard percentiles at each grain.",
        availability: "Pinned v1.20 (December 2025) ArcGIS tract and county layers. Runtime downloads verify revisions and cache them locally.",
        officialUrl: "https://hazards.fema.gov/nri/data-resources",
        additionalUrls: [
          { label: "Tract layer", href: "https://www.arcgis.com/home/item.html?id=9da4eeb936544335a6db0cd7a8448a51&sublayer=0" },
          { label: "County layer", href: "https://www.arcgis.com/home/item.html?id=39485e8035d446a5bff03259508ae355&sublayer=0" },
        ],
        coverage: "85,154 tracts and 3,232 counties/county equivalents in the pinned source layers.",
        noGuideReason: "FEMA National Flood Hazard Layer is a different dataset; a National Risk Index guide has not passed review.",
      },
      {
        name: "County Health Rankings & Roadmaps 2025",
        group: "Core hazard map",
        role: "Official county Community Conditions Health Group plus a separate NPPES-derived mental-health supplement used in County Fit.",
        availability: "Pinned 2025 ArcGIS county layer and 2025 supplemental file; the supplement is acquired by maintainers, not at app startup.",
        officialUrl: "https://www.countyhealthrankings.org/health-data/methodology-and-sources/data-documentation",
        additionalUrls: [
          { label: "Community Conditions county layer", href: "https://p3eplmys2rvchkjx.svcs.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/County%20Health%20Rankings%202025/FeatureServer/2" },
          { label: "Mental-health supplement", href: "https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_supplement_20260325%5B1%5D.csv" },
        ],
        noGuideReason: "The NPPES registry guide does not cover these CHR&R published products; guide review is pending.",
      },
      {
        name: "BEA Regional Price Parities",
        group: "County fit and context",
        role: "2024 MSA all-items RPP for the map and county fit; official state RPP supplements nonmetro ranking assignments.",
        availability: "Pinned MARPP and SARPP 2024 archives. BEA map context is optional and can be null when its verified download fails.",
        officialUrl: "https://www.bea.gov/data/prices-inflation/regional-price-parities-state-and-metro-area",
        additionalUrls: [
          { label: "MSA archive", href: "https://apps.bea.gov/regional/zip/MARPP.zip" },
          { label: "State archive", href: "https://apps.bea.gov/regional/zip/SARPP.zip" },
        ],
        noGuideReason: "The existing BEA GDP and income guide does not cover Regional Price Parities.",
      },
      {
        name: "Realtor.com Research Data",
        group: "Private local input",
        role: "County home-cost month and trailing-12-month history for Home Costs, Affordability, and Custom Fit.",
        availability: "Private, explicit local import of a checksum-approved file for acknowledged personal use. No rows are packaged, fetched automatically, or exposed by this site.",
        officialUrl: "https://www.realtor.com/research/data/",
        noGuideReason: "Reuse is restricted and the data is available only through the user's private local import.",
      },
      {
        name: "Census Population Estimates Program",
        group: "Pinned county ranking",
        role: "2025 county population for ranking eligibility and context, including the fixed 25,000-person floor.",
        availability: "Pinned 2025 county totals, acquired by maintainers and packaged only as derived county reference values.",
        officialUrl: "https://www.census.gov/programs-surveys/popest.html",
        additionalUrls: [{ label: "Pinned county file", href: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/totals/co-est2025-alldata.csv" }],
        noGuideReason: "A Census PEP county-totals guide has not passed catalog review.",
      },
      {
        name: "FBI Crime Data Explorer",
        group: "Pinned county ranking",
        role: "2023–2025 attributed agency crime and reporting-population coverage for Safety Factors.",
        availability: "Pinned agency response manifest and manually staged reference archives; suppression and less than 90% coverage remain null.",
        officialUrl: "https://cde.ucr.cjis.gov/LATEST/webapp/",
        evidenceUrl: "https://github.com/hypertrial/househunter/blob/eea3dfffb5bd728afff4e63edda27959e7d86f97/config/ranking/source-lock-v2.json",
        noGuideReason: "The existing FBI guide starts with state estimates, not this pinned agency response and archive contract.",
      },
      {
        name: "EPA Safe Drinking Water Information System",
        group: "Pinned county ranking",
        role: "Public-water-system inventory and violation records contributing to Safety Factors.",
        availability: "Pinned 2026Q2 bulk submission staged by maintainers; excludes private wells and is not real-time water-quality measurement.",
        officialUrl: "https://echo.epa.gov/tools/data-downloads/sdwa-download-summary",
        noGuideReason: "The existing ECHO web-service guide is not the pinned SDWIS bulk archive used here.",
      },
      {
        name: "EPA Community Water System Service Areas",
        group: "Pinned county ranking",
        role: "Modeled and supplied public-water boundaries allocated to 2020 Census block population for county coverage context.",
        availability: "Pinned version 2.1 GeoPackage and block table, acquired by maintainers; insufficient allocatable coverage remains null.",
        officialUrl: "https://www.epa.gov/ground-water-and-drinking-water/public-water-system-service-areas",
        noGuideReason: "A guide for the service-area model and allocation table has not passed review.",
      },
      {
        name: "HRSA Area Health Resources Files",
        group: "Pinned county ranking",
        role: "2024–2025 county primary-care and dental provider supply for Health utility.",
        availability: "Pinned AHRF archive acquired by maintainers; provider counts are availability proxies.",
        officialUrl: "https://data.hrsa.gov/data/download",
        noGuideReason: "An AHRF county guide has not passed catalog review.",
      },
      {
        name: "Census ACS 2024 Five-Year Estimates",
        group: "Pinned county ranking",
        role: "Housing age/value and property tax, commute context, and county-to-CBSA geography used by the ranking and housing-stock references.",
        availability: "Pinned table-based summary files B25034, B25035, B25103, B25077, and B08303; maintainer-generated housing-stock assets are bundled, not fetched at runtime.",
        officialUrl: "https://www.census.gov/programs-surveys/acs/data/summary-file.html",
        coverage: "Tract and county housing stock across the 50 states, DC, and Puerto Rico; separate county ranking inputs.",
        noGuideReason: "The existing ACS guide starts from the Data API, not these pinned table-based Summary File artifacts.",
      },
      {
        name: "BLS Quarterly Census of Employment and Wages",
        group: "Pinned county ranking",
        role: "County employment and wage context for Opportunity utility.",
        availability: "Pinned final 2024 and 2025 county high-level archives acquired by maintainers.",
        officialUrl: "https://www.bls.gov/cew/",
        noGuideReason: "The BLS Public Data API guide covers a different access product; a QCEW archive guide is pending.",
      },
      {
        name: "FCC Broadband Data Collection",
        group: "Pinned county ranking",
        role: "December 2025 terrestrial fixed 100/20 served share of broadband-serviceable locations for Opportunity utility.",
        availability: "Pinned county summary archive staged by maintainers; Location Fabric is denied and this is not population coverage.",
        officialUrl: "https://www.fcc.gov/BroadbandData",
        noGuideReason: "The existing National Broadband Map guide uses the API, not the manually staged county summary archive.",
      },
      {
        name: "NOAA U.S. Climate Normals",
        group: "Pinned county ranking",
        role: "1991–2020 annual and monthly in-county station climate values for optional filters.",
        availability: "Pinned v1.0.1 station archives acquired by maintainers; climate is null without a fully qualifying station.",
        officialUrl: "https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals",
        noGuideReason: "A Climate Normals station archive guide has not passed catalog review.",
      },
      {
        name: "Census TIGER/Line",
        group: "Geography and mountain inputs",
        role: "2025 county boundaries for ranking and 2020 census blocks with population/internal points for Mountain Magnitude.",
        availability: "Pinned 2025 national county ZIP plus 51 state/DC 2020 block extracts; Mountain build is maintainer-only.",
        officialUrl: "https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html",
        coverage: "50 states and DC; 2020 block and 2025 county vintages are kept distinct.",
        guideId: "census-tiger-line",
      },
      {
        name: "USGS 3D Elevation Program",
        group: "Geography and mountain inputs",
        role: "Elevation rasters for Mountain Magnitude terrain relief, slope, and ruggedness.",
        availability: "Pinned 1,645 reviewed 1-arc-second tiles; maintainer-only acquisition and no normal startup fetch.",
        officialUrl: "https://www.usgs.gov/3d-elevation-program",
        evidenceUrl: "https://github.com/hypertrial/househunter/blob/eea3dfffb5bd728afff4e63edda27959e7d86f97/config/mountain/source-lock-v2.json",
        noGuideReason: "A 3DEP elevation-tile guide has not passed catalog review.",
      },
      {
        name: "USGS Protected Areas Database",
        group: "Geography and mountain inputs",
        role: "PAD-US 4.1 public-access polygons for Mountain Magnitude open-land context.",
        availability: "Pinned anonymous MapServer object inventory; maintainer-only capture.",
        officialUrl: "https://www.usgs.gov/programs/gap-analysis-project/science/pad-us-data-download",
        evidenceUrl: "https://github.com/hypertrial/househunter/blob/eea3dfffb5bd728afff4e63edda27959e7d86f97/config/mountain/source-lock-v2.json",
        noGuideReason: "A PAD-US 4.1 layer guide has not passed catalog review.",
      },
      {
        name: "USGS National Transportation Database trails",
        group: "Geography and mountain inputs",
        role: "Mapped hiking trail segments for Mountain Magnitude access distance and density.",
        availability: "Pinned 51 state/DC GPKG extracts dated 2026-02-12; maintainer-only build input.",
        officialUrl: "https://www.usgs.gov/national-digital-trails/how-access-or-view-usgs-trails-dataset",
        evidenceUrl: "https://github.com/hypertrial/househunter/blob/eea3dfffb5bd728afff4e63edda27959e7d86f97/config/mountain/source-lock-v2.json",
        noGuideReason: "A National Transportation Database trail-extract guide has not passed review.",
      },
      {
        name: "Appalachian Regional Commission county list",
        group: "Pinned county ranking",
        role: "Appalachia region membership for County Fit filters.",
        availability: "Reviewed 2026 county list packaged as a fixed FIPS reference.",
        officialUrl: "https://www.arc.gov/appalachian-counties-served-by-arc/",
        evidenceUrl: "https://github.com/hypertrial/househunter/blob/eea3dfffb5bd728afff4e63edda27959e7d86f97/config/ranking/appalachia-counties.json",
        noGuideReason: "A guide for the ARC county list has not passed catalog review.",
      },
      {
        name: "State homeschool law references",
        group: "Pinned county ranking",
        role: "Official state statute references inform HouseHunter's approximate, project-authored Homeschool Policy Fit rubric.",
        availability: "Pinned state-level rubric reviewed 2026-09-16; it is a preference proxy, not legal advice or current compliance guidance.",
        officialUrl: "https://www.usa.gov/state-governments",
        additionalUrls: [{
          label: "51 Pinned Official Statute Citations",
          href: "https://github.com/hypertrial/househunter/blob/eea3dfffb5bd728afff4e63edda27959e7d86f97/config/ranking/homeschool-policy-v1.json",
        }],
        coverage: "50 states and DC; the pinned rubric contains each jurisdiction's official statute URL.",
        noGuideReason: "A project-authored preference rubric is outside the external dataset catalog.",
      },
      {
        name: "Census Geocoder",
        group: "On-demand address lookup",
        role: "Matches a user-entered address or fallback coordinates to its 2020 Census tract.",
        availability: "Called only on explicit lookup; a provider outage is not treated as an empty match.",
        officialUrl: "https://geocoding.geo.census.gov/geocoder/",
        noGuideReason: "A Census Geocoder lookup guide has not passed catalog review.",
      },
      {
        name: "OpenStreetMap Nominatim",
        group: "On-demand address lookup",
        role: "Fallback street search only when Census returns a valid empty address-match list; Census still supplies the tract ID.",
        availability: "Optional HTTPS endpoint, disableable by operator; approximate road matches require user confirmation.",
        officialUrl: "https://nominatim.openstreetmap.org/",
        noGuideReason: "Nominatim address search is a different service from the existing OSM Overpass guide.",
      },
    ],
  },
  {
    slug: "rockyroad",
    title: "RockyRoad",
    summary: "Plan Canada–U.S. road trips with hosted search and routing or an explicitly built local OpenStreetMap dataset.",
    status: "alpha",
    sourceUrl: "https://github.com/hypertrial/rockyroad",
    sourceRevision: "5acf684a8de1ea0cdb85506ecda72dbe73e150b3",
    sourceEvidenceUrl: "https://github.com/hypertrial/rockyroad/blob/5acf684a8de1ea0cdb85506ecda72dbe73e150b3/docs/data-build.md",
    reviewedAt: "2026-09-28",
    sourceIntro: "RockyRoad defaults to hosted routing and search. An explicit local mode replaces them with artifacts built from allow-listed OSM extracts; it does not silently fail over between modes. Map presentation tiles are separate from the product-data sources below.",
    sources: [
      {
        name: "OpenRouteService and VROOM",
        group: "Hosted mode",
        role: "Driving directions and ordered trip stops.",
        availability: "Default hosted routing requires ROCKYROAD_ORS_API_KEY; quota, outage, or missing key can block route building.",
        officialUrl: "https://openrouteservice.org/",
        additionalUrls: [{ label: "Hosted optimization API", href: "https://api.heigit.org/vroom/v0/optimization" }],
        coverage: "Canada and United States within the hosted provider's route limits.",
        noGuideReason: "A provider-specific directions and optimization guide has not passed catalog review.",
      },
      {
        name: "Photon",
        group: "Hosted mode",
        role: "Place search and stop selection, with cached and deduplicated results.",
        availability: "Default hosted public demo service; usage limits and outages can interrupt search.",
        officialUrl: "https://photon.komoot.io/",
        noGuideReason: "A Photon geocoding guide has not passed catalog review.",
      },
      {
        name: "OpenStreetMap regional extracts via Geofabrik",
        group: "Local mode",
        role: "Local places and road graph built from OSM PBF files for search and routing.",
        availability: "Optional explicit local build; sample profile pins Prince Edward Island, full profile allows Canada and U.S. extracts. No runtime hosted-geocoder or routing call in this mode.",
        officialUrl: "https://download.geofabrik.de/north-america.html",
        additionalUrls: [{ label: "OSM data and license", href: "https://www.openstreetmap.org/copyright" }],
        coverage: "PEI sample or Canada plus United States, depending on the selected extract profile.",
        evidenceUrl: "https://github.com/hypertrial/rockyroad/blob/5acf684a8de1ea0cdb85506ecda72dbe73e150b3/config/regions.yaml",
        noGuideReason: "The existing OSM Overpass guide does not cover Geofabrik PBF extracts.",
      },
    ],
  },
  {
    slug: "stackingsats",
    title: "StackingSats",
    summary: "Archived Bitcoin accumulation research site and Python library for testing fixed-budget allocation strategies.",
    status: "archived",
    archiveUrl: "https://stackingsats.org/",
    sourceUrl: "https://github.com/hypertrial/stacksats",
    sourceRevision: "9ba73643c4478ddd92650557a90e91e64674f587",
    sourceEvidenceUrl: "https://github.com/hypertrial/stacksats/blob/9ba73643c4478ddd92650557a90e91e64674f587/docs/data-source.md",
    reviewedAt: "2026-09-28",
    sourceIntro: "The archived website is informational. The historical StackSats library uses a manually fetched, hash-verified BRK parquet and can optionally call market-price helpers. Backtests never imply that the archived site serves a live feed.",
    sources: [
      {
        name: "Bitcoin Research Kit merged metrics",
        group: "Historical library data",
        role: "Canonical long-format Bitcoin metrics projected into a local wide parquet for strategy research and backtests.",
        availability: "Pinned 2026-03-15 Google Drive artifact; explicit fetch verifies 1.16 GB size and SHA-256. Runtime reads local parquet and never auto-downloads.",
        officialUrl: "https://github.com/bitcoinresearchkit/brk",
        additionalUrls: [{ label: "Pinned parquet artifact", href: "https://drive.google.com/file/d/1jKRRU7l9kOMdGI_hIJGg02X3jWTMPJsw/view?usp=sharing" }],
        evidenceUrl: "https://github.com/hypertrial/stacksats/blob/9ba73643c4478ddd92650557a90e91e64674f587/stacksats/assets/brk_data_manifest.json",
        coverage: "Snapshot documents 2009-01-03 through 2026-03-13 daily metrics.",
        noGuideReason: "A BRK merged-metrics guide has not passed the Data catalog's access and reuse review.",
      },
      {
        name: "CoinGecko",
        group: "Optional library price helpers",
        role: "First-choice current BTC/USD quote for export helpers and historical-date lookup helper.",
        availability: "Optional network extra and explicit helper calls only; no archived-website feed.",
        officialUrl: "https://www.coingecko.com/en/api",
        evidenceUrl: "https://github.com/hypertrial/stacksats/blob/9ba73643c4478ddd92650557a90e91e64674f587/stacksats/data/btc_price_fetcher.py",
        noGuideReason: "A CoinGecko price API guide has not passed catalog review.",
      },
      {
        name: "Coinbase",
        group: "Optional library price helpers",
        role: "Fallback current BTC/USD spot quote for export helpers.",
        availability: "Optional network extra and explicit helper calls only; no archived-website feed.",
        officialUrl: "https://api.coinbase.com/v2/prices/BTC-USD/spot",
        noGuideReason: "A Coinbase spot-price guide has not passed catalog review.",
      },
      {
        name: "Bitstamp",
        group: "Optional library price helpers",
        role: "Fallback current BTC/USD ticker price for export helpers.",
        availability: "Optional network extra and explicit helper calls only; no archived-website feed.",
        officialUrl: "https://www.bitstamp.net/api/",
        noGuideReason: "A Bitstamp ticker guide has not passed catalog review.",
      },
      {
        name: "Kraken",
        group: "Optional library price helpers",
        role: "Fallback current BTC/USD ticker price for export helpers.",
        availability: "Optional network extra and explicit helper calls only; no archived-website feed.",
        officialUrl: "https://docs.kraken.com/api/docs/rest-api/get-ticker-information/",
        noGuideReason: "A Kraken ticker guide has not passed catalog review.",
      },
      {
        name: "Binance",
        group: "Optional library price helpers",
        role: "Fallback current BTC/USDT price and historical kline lookup helper.",
        availability: "Optional network extra and explicit helper calls only; BTC/USDT is a proxy for USD, not the same quote.",
        officialUrl: "https://developers.binance.com/docs/binance-spot-api-docs/rest-api/market-data-endpoints",
        noGuideReason: "A Binance market-data guide has not passed catalog review.",
      },
    ],
  },
] as const;
