import nationalWarningSystems from "./national-warning-systems.json";

// Reviewed against TravelCanary's generated source inventory and its authored
// source registries. This is a static editorial snapshot, not runtime health.
export const travelCanary = {
  slug: "travelcanary",
  title: "TravelCanary",
  summary: "A destination-level view of current hazards and local conditions across 45 European countries.",
  status: "beta",
  liveUrl: "https://travelcanary.org/",
  sourceUrl: "https://github.com/hypertrial/travelcanary",
  sourceRevision: "1ff2fdfa06b38880175a03aed10cfe60352bd0f6",
  sourceEvidenceUrl: "https://github.com/hypertrial/travelcanary/blob/1ff2fdfa06b38880175a03aed10cfe60352bd0f6/data/source-inventory.json",
  reviewedAt: "2026-09-28",
  sourceIntro: "These are the source families and pinned inputs in the reviewed TravelCanary revision, including optional and unavailable connectors. A listing does not establish that a feed is running, healthy, or applicable to a destination. Warnings can contribute only within reviewed source geometry; forecasts, observations, satellite detections, news, and travel advice are context or discovery.",
  sources: [
    {
      group: "Hazard and discovery feeds",
      name: "MeteoAlarm / EUMETNET warnings",
      role: "Official severe-weather and related hazard warnings; keyless Atom primary feed and optional authenticated EDR recovery.",
      availability: "Configured. Country and destination mappings vary; EDR recovery requires a token and does not add coverage independently.",
      coverage: "European member feeds; the country-by-country active and gated mappings are listed under National warnings.",
      officialUrl: "https://meteoalarm.org/",
      guideId: "meteoalarm-atom-warnings",
    },
    {
      group: "Hazard and discovery feeds",
      name: "USGS earthquake feeds",
      role: "Primary earthquake event evidence, including the product's published application feeds and ShakeMap context.",
      availability: "Configured; individual destinations receive evidence only when the event and coverage checks apply.",
      officialUrl: "https://earthquake.usgs.gov/",
      guideId: "usgs-earthquakes",
    },
    {
      group: "Hazard and discovery feeds",
      name: "Copernicus EFFIS",
      role: "Fire-danger forecasts and active-fire context; danger forecast does not confirm a fire.",
      availability: "Configured; active-fire detections and perimeters are complementary and do not establish official wildfire-warning coverage.",
      officialUrl: "https://forest-fire.emergency.copernicus.eu/",
      guideIds: [
        { id: "effis-fire-danger-forecast", label: "Fire danger forecast" },
        { id: "effis-active-fire-hotspots", label: "Active-fire hotspots" },
        { id: "effis-burned-area-perimeters", label: "Optional burned-area perimeters" },
      ],
    },
    {
      group: "Hazard and discovery feeds",
      name: "NASA FIRMS thermal detections",
      role: "Satellite hotspot context alongside EFFIS active-fire data; detections are not confirmed wildfire perimeters.",
      availability: "Optional; the FIRMS path needs an operator MAP_KEY and cannot establish warning coverage.",
      officialUrl: "https://firms.modaps.eosdis.nasa.gov/",
      guideId: "nasa-firms",
    },
    {
      group: "Hazard and discovery feeds",
      name: "Copernicus EMS Rapid Mapping",
      role: "Complementary maps for wildfire, flood, industrial, and other emergency events.",
      availability: "Configured as non-blocking context; a Rapid Mapping activation is not current warning coverage.",
      officialUrl: "https://mapping.emergency.copernicus.eu/",
      guideId: "copernicus-rapid-mapping-activations",
    },
    {
      group: "Hazard and discovery feeds",
      name: "GDACS disaster alerts",
      role: "Hourly disaster-event discovery used to route checks to independent official sources.",
      availability: "Configured for discovery only; GDACS never changes risk or satisfies warning coverage.",
      officialUrl: "https://www.gdacs.org/",
      guideId: "gdacs-disaster-alerts",
    },
    {
      group: "Hazard and discovery feeds",
      name: "Copernicus Global Flood Monitoring",
      role: "Satellite flood corroboration.",
      availability: "Environment-gated and non-blocking; no official flood-warning coverage credit.",
      officialUrl: "https://global-flood.emergency.copernicus.eu/",
      guideIds: [
        { id: "copernicus-gfm-flood-layers", label: "Satellite flood extent and quality" },
        { id: "copernicus-glofas-flood-outlook", label: "Optional GloFAS forecast targeting" },
      ],
    },
    {
      group: "Hazard and discovery feeds",
      name: "EMSC Seismic Portal",
      role: "Preliminary earthquake fallback when primary USGS evidence is unavailable.",
      availability: "Configured as fallback; unmatched reports cannot replace ShakeMap intensity or establish monitoring coverage.",
      officialUrl: "https://www.seismicportal.eu/",
      guideId: "emsc-earthquake-events",
    },
    {
      group: "Hazard and discovery feeds",
      name: "SLF avalanche bulletins",
      role: "Official avalanche warnings for mapped Swiss bulletin regions.",
      availability: "Configured; limited to destinations intersecting reviewed bulletin geometry.",
      officialUrl: "https://www.slf.ch/en/avalanche-bulletin-and-snow-situation/",
      guideId: "slf-avalanche-bulletins",
    },
    {
      group: "Hazard and discovery feeds",
      name: "Avalanche.report / EAWS bulletins",
      role: "Official avalanche warnings for licensed, reviewed Alpine regions.",
      availability: "Configured only for mapped feed regions; additional region intersections remain gated pending bulletin verification.",
      officialUrl: "https://avalanche.report/",
      guideId: "avalanche-report-bulletins",
    },
    {
      group: "Hazard and discovery feeds",
      name: "European Environment Agency air quality",
      role: "Observed station pollutants and European AQI context.",
      availability: "Configured with partial monitoring only at mapped operational stations; modeled or gap-filled values cannot establish an all-clear.",
      officialUrl: "https://airindex.eea.europa.eu/",
      guideId: "eea-air-quality-index-stations",
    },
    {
      group: "Hazard and discovery feeds",
      name: "GDELT news discovery",
      role: "Corroborated civil-unrest and security news context.",
      availability: "Gated; requires three independently owned reviewed publishers and never establishes monitoring coverage.",
      officialUrl: "https://www.gdeltproject.org/",
      noGuideReason: "The pinned GDELT Geo 2.0 API returned HTTP 404 for a bounded query on 2026-09-28; a runnable exact-feed example could not be verified.",
    },
    {
      group: "Hazard and discovery feeds",
      name: "Vigicrues flood warnings",
      role: "Official French river-section flood warnings.",
      availability: "Configured; only destinations mapped to official river sections qualify.",
      officialUrl: "https://www.vigicrues.gouv.fr/",
      guideId: "vigicrues-flood-vigilance-rss",
    },
    {
      group: "Hazard and discovery feeds",
      name: "Swiss FOEN flood-warning map",
      role: "Official Swiss flood-warning map sampled at destination geometry.",
      availability: "Configured for the mapped Swiss footprint; a warning-map pixel is not a local water-level measurement.",
      officialUrl: "https://www.hydrodaten.admin.ch/",
      guideId: "foen-flood-warning-map",
    },
    {
      group: "Hazard and discovery feeds",
      name: "Austria eHYD flood stages",
      role: "Official flood-warning stages at mapped hydrographic stations.",
      availability: "Configured; raw water levels do not score as warnings.",
      officialUrl: "https://ehyd.gv.at/",
      guideId: "ehyd-current-flood-stages",
    },
    {
      group: "Hazard and discovery feeds",
      name: "NASA EONET",
      role: "Recent wildfire and volcano event context.",
      availability: "Environment-gated, non-blocking, and not a local warning source.",
      officialUrl: "https://eonet.gsfc.nasa.gov/",
      guideId: "nasa-eonet-events",
    },
    {
      group: "Hazard and discovery feeds",
      name: "Copernicus European Drought Observatory",
      role: "Dekadal agricultural and ecosystem drought context.",
      availability: "Environment-gated; not an immediate emergency warning.",
      officialUrl: "https://drought.emergency.copernicus.eu/",
      guideId: "copernicus-edo-drought-indicator",
    },
    {
      group: "Hazard and discovery feeds",
      name: "UK FCDO travel advice",
      role: "Whole-country security and travel-advice context.",
      availability: "Environment-gated; the text does not imply sub-country warning geometry.",
      officialUrl: "https://www.gov.uk/foreign-travel-advice",
      guideId: "fcdo-travel-advice",
    },
    {
      group: "Local conditions",
      name: "Open-Meteo weather forecasts",
      role: "Hourly modeled point-weather forecasts for local conditions.",
      availability: "Configured but restricted to accepted noncommercial use and local-conditions activation; forecasts are not observations or warnings.",
      officialUrl: "https://open-meteo.com/en/docs",
      guideId: "open-meteo-weather-forecast",
    },
    {
      group: "Local conditions",
      name: "Open-Meteo air-quality forecasts and Copernicus CAMS",
      role: "Modeled air-quality, dust, and UV context served by Open-Meteo using CAMS data.",
      availability: "Configured but restricted to accepted noncommercial use and local-conditions activation; model values are not station observations.",
      officialUrl: "https://open-meteo.com/en/docs/air-quality-api",
      additionalUrls: [{ label: "Copernicus Atmosphere Monitoring Service", href: "https://atmosphere.copernicus.eu/" }],
      guideId: "open-meteo-air-quality",
    },
    {
      group: "Local conditions",
      name: "Open-Meteo marine forecasts",
      role: "Nearby offshore wave and marine forecasts for reviewed coastal destinations.",
      availability: "Configured but restricted to accepted noncommercial use and local-conditions activation; unsupported coasts remain outside the mapped product.",
      officialUrl: "https://open-meteo.com/en/docs/marine-weather-api",
      guideId: "open-meteo-marine",
    },
    {
      group: "Local conditions",
      name: "MET Norway Locationforecast",
      role: "Fallback point weather forecast.",
      availability: "Configured when local conditions are activated; forecast values are not observations or official warnings.",
      officialUrl: "https://api.met.no/weatherapi/locationforecast/2.0/documentation",
      additionalUrls: [{ label: "MET Norway", href: "https://www.met.no/en" }],
      guideId: "met-norway-locationforecast",
    },
    {
      group: "Local conditions",
      name: "NOAA Aviation Weather Center METAR and station cache",
      role: "Airport weather observations at reviewed representative stations; the pinned station cache maps airports to destinations.",
      availability: "Configured when local conditions are activated; airport readings are not destination-wide weather conditions or aviation advice.",
      officialUrl: "https://aviationweather.gov/data/api/",
      additionalUrls: [{ label: "Aviation Weather Center", href: "https://aviationweather.gov/" }],
      guideId: "awc-metar-stations",
    },
    {
      group: "Local conditions",
      name: "IPMA weather observations and seismic records",
      role: "Portuguese station observations and recent regional earthquake context.",
      availability: "Configured but restricted to accepted noncommercial use and local-conditions activation; measurements do not establish warning coverage.",
      officialUrl: "https://api.ipma.pt/",
      guideIds: [
        { id: "ipma-weather-station-observations", label: "Weather stations" },
        { id: "ipma-seismic-observations", label: "Regional earthquakes" },
      ],
    },
    {
      group: "Local conditions",
      name: "IGN regional earthquakes",
      role: "Candidate Spanish regional earthquake context.",
      availability: "Gated and not connected until RSS event time, corrections, and deletion lifecycle are verified.",
      officialUrl: "https://www.ign.es/web/social-rss",
      guideId: "ign-spain-earthquake-rss",
    },
    {
      group: "Local conditions",
      name: "ARSO hydrology",
      role: "Provisional Slovenian river observations at reviewed stations.",
      availability: "Configured for local conditions; reference-level crossings are factual context, not official flood warnings.",
      officialUrl: "https://www.arso.gov.si/vode/podatki/hidro_podatki_xml.html",
      guideId: "arso-current-hydrology",
    },
    {
      group: "Local conditions",
      name: "Ireland OPW water levels",
      role: "Provisional Irish gauge observations relative to local gauge zero.",
      availability: "Configured for local conditions; unchecked station data are not flood warnings.",
      officialUrl: "https://waterlevel.ie/page/api/",
      additionalUrls: [{ label: "OPW waterlevel.ie", href: "https://waterlevel.ie/" }],
      guideId: "opw-ireland-water-levels",
    },
    {
      group: "Local conditions",
      name: "Rijkswaterstaat Waterdata",
      role: "Dutch station water levels with quality-code and NAP-datum checks; pinned station metadata maps locations.",
      availability: "Configured for local conditions; observations are not flood warnings.",
      officialUrl: "https://rijkswaterstaatdata.nl/waterdata/",
      guideId: "rijkswaterstaat-current-water-levels",
    },
    {
      group: "Local conditions",
      name: "VMM Waterinfo",
      role: "Candidate Belgian river-level observations.",
      availability: "Gated: reviewed live group yielded rainfall, while water-level groups, quality codes, mappings, and HIC access remain unapproved.",
      officialUrl: "https://www.waterinfo.vlaanderen.be/default.aspx?path=Public%2FOver+waterinfo%2FFAQ+open+data",
      noGuideReason: "Waterinfo says automated VMM requests require a dedicated token requested from the operator; no authorized water-level token or reviewed level group was available for an exact runnable example. The tested anonymous group contained rainfall, not this feed.",
    },
    {
      group: "Local conditions",
      name: "Lithuanian Hydrometeorological Service",
      role: "Candidate river and station observations.",
      availability: "Gated until exact station mappings and vertical-reference metadata are reviewed.",
      officialUrl: "https://api.meteo.lt/",
      guideId: "meteo-lt-hydrology-observations",
    },
    {
      group: "Local conditions",
      name: "Finnish Environment Institute SYKE",
      role: "Candidate hydrological station observations.",
      availability: "Gated pending OData fixture, quality flag, datum, and station-mapping review.",
      officialUrl: "https://www.syke.fi/en/environmental-data/open-web-services/environmental-data-apis",
      guideId: "syke-hydrology-water-levels",
    },
    {
      group: "Local conditions",
      name: "Cyprus air-quality network",
      role: "Candidate air-quality station observations.",
      availability: "Gated pending local-time, instrument-flag, and station-mapping review.",
      officialUrl: "https://www.airquality.dli.mlsi.gov.cy/",
      noGuideReason: "Cyprus publishes this feed under CC BY-SA, but its official all-stations JSON endpoints returned HTTP 403 to a bounded automated request on 2026-09-28; an exact runnable Python example could not be verified.",
    },
    {
      group: "Local conditions",
      name: "Bulgarian NIMH hydrology",
      role: "Candidate daily hydrological observations.",
      availability: "Gated pending timestamp, reuse, and station-area review; daily values cannot imply current flood warnings.",
      officialUrl: "https://info.meteo.bg/openData/",
      noGuideReason: "The official daily runoff CSV and Python access work, but NIMH's current open-data pages no longer expose the reuse conditions indexed in earlier copies; permitted analysis cannot be confirmed from a live source.",
    },
    {
      group: "Local conditions",
      name: "Fintraffic Digitraffic",
      role: "Current accident-associated road closures matched by official geometry.",
      availability: "Configured for local conditions; nearby context is not complete disruption coverage or route advice.",
      officialUrl: "https://www.digitraffic.fi/en/road-traffic/",
      guideId: "fintraffic-digitraffic-road-messages",
    },
    {
      group: "Local conditions",
      name: "SMHI water-shortage information",
      role: "Candidate Swedish water-shortage messages.",
      availability: "Gated until informational-message validity and reuse lifecycle fixtures pass review.",
      officialUrl: "https://opendata-download-warnings.smhi.se/ibww/api/version/1",
      guideId: "smhi-water-shortage-messages",
    },
    {
      group: "Local conditions",
      name: "Krisinformation infrastructure notices",
      role: "Official Swedish infrastructure and crisis notices, reduced to fixed factual categories.",
      availability: "Configured for local conditions; regional notices do not prove a destination-wide interruption.",
      officialUrl: "https://www.krisinformation.se/",
      guideId: "krisinformation-news",
    },
    {
      group: "Local conditions",
      name: "NDW open traffic data",
      role: "Dutch serious road incidents and complete closures intersecting destinations.",
      availability: "Configured for local conditions; not route advice.",
      officialUrl: "https://opendata.ndw.nu/",
      guideId: "ndw-road-closures",
    },
    {
      group: "Local conditions",
      name: "Autobahn GmbH traffic information",
      role: "German motorway closures and warnings intersecting destinations.",
      availability: "Configured but restricted to accepted operator use and local-conditions activation; not complete transport monitoring.",
      officialUrl: "https://www.autobahn.de/",
      noGuideReason: "The operator's API portal requires an Autobahn employee ID; the community autobahn.api.bund.dev endpoint is not an operator-published reuse grant for the exact closure feed, so access and terms do not qualify.",
    },
    {
      group: "Local conditions",
      name: "Electricity Authority of Cyprus",
      role: "Candidate current and scheduled power interruptions by district.",
      availability: "Gated: five public district pages exceeded the reviewed eight-second source budget.",
      officialUrl: "https://www.eac.com.cy/EN/RegulatedActivities/Distribution/PowerInterruptions/Pages/Faultsandscheduledinterruptions.aspx?District=0",
      noGuideReason: "The reviewed official district pages exceeded the product's eight-second source budget, and no official machine-readable outage contract or terms permitting automated analysis were verified for a runnable exact-feed guide.",
    },
    {
      group: "Local conditions",
      name: "Enemalta outages",
      role: "Candidate Maltese current and planned electricity interruptions.",
      availability: "Gated: the official planned-outage response exceeded the approved 512 KiB limit.",
      officialUrl: "https://www.enemalta.com.mt/planned-power-cuts/",
      noGuideReason: "The official terms allow only personal, noncommercial reproduction of true copies and do not establish permission for transformed outage analysis; the planned-outage response also exceeded the product's 512 KiB gate.",
    },
    {
      group: "Local conditions",
      name: "PSE Energy Compass",
      role: "Polish national electricity-use recommendations, not local outages.",
      availability: "Configured for local conditions; advice describes system-wide conditions only.",
      officialUrl: "https://www.energetycznykompas.pl/",
      guideId: "pse-energy-compass",
    },
    {
      group: "Pinned inputs",
      name: "GeoNames destination gazetteer",
      role: "Pinned place names and representative coordinates for the 679-destination catalog.",
      availability: "Pinned catalog input, not a live feed; regional matching areas are TravelCanary approximations.",
      officialUrl: "https://download.geonames.org/export/dump/",
      evidenceUrl: "https://github.com/hypertrial/travelcanary/blob/1ff2fdfa06b38880175a03aed10cfe60352bd0f6/data/review-inputs/europe-expansion-catalog.json",
      guideId: "geonames-daily-gazetteer",
    },
    {
      group: "Pinned inputs",
      name: "Eurostat GISCO NUTS 2024 geometry",
      role: "Pinned NUTS-2 region mapping used to match destinations to MeteoAlarm warnings.",
      availability: "Pinned geographic input; a regional polygon alone does not establish warning coverage.",
      officialUrl: "https://gisco-services.ec.europa.eu/distribution/v2/nuts/nuts-2024-files.html",
      evidenceUrl: "https://github.com/hypertrial/travelcanary/blob/1ff2fdfa06b38880175a03aed10cfe60352bd0f6/data/catalog-metadata.json",
      guideId: "eurostat-gisco-nuts-2024",
    },
    {
      group: "Pinned inputs",
      name: "EAWS avalanche regions",
      role: "Pinned avalanche micro-region geometry used for candidate bulletin-to-destination intersections.",
      availability: "Pinned geographic review input; new region matches remain gated until bulletin and seasonal scope review.",
      officialUrl: "https://eaws.gitlab.io/eaws-regions/micro-regions.geojson",
      evidenceUrl: "https://github.com/hypertrial/travelcanary/blob/1ff2fdfa06b38880175a03aed10cfe60352bd0f6/data/review-inputs/eaws-expansion-review.json",
      guideId: "eaws-avalanche-regions",
    },
    {
      group: "Pinned inputs",
      name: "Smithsonian Global Volcanism Program Holocene volcanoes",
      role: "Pinned volcano locations used to decide where volcanic hazard checks apply.",
      availability: "Pinned reference data, not a live eruption feed.",
      officialUrl: "https://volcano.si.edu/gvp_webservices.cfm",
      evidenceUrl: "https://github.com/hypertrial/travelcanary/blob/1ff2fdfa06b38880175a03aed10cfe60352bd0f6/data/review-inputs/gvp-holocene.json",
      guideId: "smithsonian-gvp-volcanoes",
    },
    // National warning partitions are a separate, explicitly reviewed matrix.
    // Each country entry below names every configured, gated, or blocked system.
    {
      group: "National warnings",
      name: "Andorra (AD) warning systems",
      role: "Official national and direct warning sources reviewed for Andorra.",
      availability: "National civil-alert partition not enabled; 1 active, 2 gated systems listed.",
      details: "MeteoAlarm keyless Atom warning feed (active; MeteoAlarm primary); MeteoAlarm authenticated EDR recovery (credential-gated; MeteoAlarm fallback); Andorra weather alerts (evidence-gated; official link/review only).",
      officialUrl: "https://www.meteoalarm.org/",
      additionalUrls: [
        { label: "Andorra weather alerts", href: "https://www.meteo.ad/en/Alerts" },
      ],
      systems: nationalWarningSystems.countries.AD,
    },
    {
      group: "National warnings",
      name: "Albania (AL) warning systems",
      role: "Official national and direct warning sources reviewed for Albania.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "Institute of Geosciences (evidence-gated; official link/review only).",
      officialUrl: "https://geo.edu.al/",
      systems: nationalWarningSystems.countries.AL,
    },
    {
      group: "National warnings",
      name: "Austria (AT) warning systems",
      role: "Official national and direct warning sources reviewed for Austria.",
      availability: "National civil-alert partition enabled; 1 active system listed.",
      details: "AT-Alert (active; national warning feed).",
      officialUrl: "https://warnung.at-alert.at/",
      systems: nationalWarningSystems.countries.AT,
    },
    {
      group: "National warnings",
      name: "Bosnia and Herzegovina (BA) warning systems",
      role: "Official national and direct warning sources reviewed for Bosnia and Herzegovina.",
      availability: "National civil-alert partition not enabled; 3 gated systems listed.",
      details: "MeteoAlarm keyless Atom warning feed (evidence-gated; official link/review only); MeteoAlarm authenticated EDR recovery (evidence-gated; official link/review only); Federal Hydrometeorological Institute (evidence-gated; official link/review only).",
      officialUrl: "https://www.meteoalarm.org/",
      additionalUrls: [
        { label: "Federal Hydrometeorological Institute", href: "https://www.fhmzbih.gov.ba/" },
      ],
      systems: nationalWarningSystems.countries.BA,
    },
    {
      group: "National warnings",
      name: "Belgium (BE) warning systems",
      role: "Official national and direct warning sources reviewed for Belgium.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "BE-Alert (evidence-gated; official link/review only).",
      officialUrl: "https://www.be-alert.be/en/",
      systems: nationalWarningSystems.countries.BE,
    },
    {
      group: "National warnings",
      name: "Bulgaria (BG) warning systems",
      role: "Official national and direct warning sources reviewed for Bulgaria.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "BG-ALERT (evidence-gated; official link/review only).",
      officialUrl: "https://bg-alert.bg/",
      systems: nationalWarningSystems.countries.BG,
    },
    {
      group: "National warnings",
      name: "Belarus (BY) warning systems",
      role: "Official national and direct warning sources reviewed for Belarus.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "Belhydromet weather information (evidence-gated; official link/review only).",
      officialUrl: "https://pogoda.by/",
      systems: nationalWarningSystems.countries.BY,
    },
    {
      group: "National warnings",
      name: "Switzerland (CH) warning systems",
      role: "Official national and direct warning sources reviewed for Switzerland.",
      availability: "National civil-alert partition not enabled; 1 blocked system listed.",
      details: "Alertswiss (blocked; official link/review only).",
      officialUrl: "https://www.alert.swiss/en/home.html",
      systems: nationalWarningSystems.countries.CH,
    },
    {
      group: "National warnings",
      name: "Cyprus (CY) warning systems",
      role: "Official national and direct warning sources reviewed for Cyprus.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "Cyprus public warning system (evidence-gated; official link/review only).",
      officialUrl: "https://www.gov.cy/moi/en/civil-defence/",
      systems: nationalWarningSystems.countries.CY,
    },
    {
      group: "National warnings",
      name: "Czechia (CZ) warning systems",
      role: "Official national and direct warning sources reviewed for Czechia.",
      availability: "National civil-alert partition enabled; 1 active system listed.",
      details: "CHMI hydrology and flash-flood risk (active; national warning feed).",
      officialUrl: "https://opendata.chmi.cz/hydrology/",
      systems: nationalWarningSystems.countries.CZ,
    },
    {
      group: "National warnings",
      name: "Germany (DE) warning systems",
      role: "Official national and direct warning sources reviewed for Germany.",
      availability: "National civil-alert partition enabled; 2 active, 1 gated systems listed.",
      details: "LHP flood warnings (active; national warning feed); BBK civil-protection RSS (evidence-gated; official link/review only); DWD direct CAP recovery (active; MeteoAlarm fallback).",
      officialUrl: "https://www.hochwasserzentralen.de/",
      additionalUrls: [
        { label: "BBK civil-protection RSS", href: "https://www.bbk.bund.de/DE/Warnung-Vorsorge/Warn-App-NINA/warn-app-nina_node.html" },
        { label: "DWD direct CAP recovery", href: "https://opendata.dwd.de/weather/alerts/cap/COMMUNEUNION_EVENT_STAT/" },
      ],
      systems: nationalWarningSystems.countries.DE,
    },
    {
      group: "National warnings",
      name: "Denmark (DK) warning systems",
      role: "Official national and direct warning sources reviewed for Denmark.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "S!RENEN (evidence-gated; official link/review only).",
      officialUrl: "https://www.sirenen.dk/",
      systems: nationalWarningSystems.countries.DK,
    },
    {
      group: "National warnings",
      name: "Estonia (EE) warning systems",
      role: "Official national and direct warning sources reviewed for Estonia.",
      availability: "National civil-alert partition not enabled; 1 blocked system listed.",
      details: "EE-ALARM (blocked; official link/review only).",
      officialUrl: "https://www.olevalmis.ee/en/",
      systems: nationalWarningSystems.countries.EE,
    },
    {
      group: "National warnings",
      name: "Spain (ES) warning systems",
      role: "Official national and direct warning sources reviewed for Spain.",
      availability: "National civil-alert partition enabled; 2 active systems listed.",
      details: "Catalonia civil-protection plans (active; national warning feed); AEMET direct CAP warnings (active; MeteoAlarm fallback).",
      officialUrl: "https://interior.gencat.cat/ca/arees_dactuacio/proteccio_civil/",
      additionalUrls: [
        { label: "AEMET direct CAP warnings", href: "https://www.aemet.es/es/rss_info/avisos/esp" },
      ],
      systems: nationalWarningSystems.countries.ES,
    },
    {
      group: "National warnings",
      name: "Finland (FI) warning systems",
      role: "Official national and direct warning sources reviewed for Finland.",
      availability: "National civil-alert partition not enabled; 1 active, 1 blocked systems listed.",
      details: "Finland public warning system (blocked; official link/review only); FMI CAP warnings (active; MeteoAlarm fallback).",
      officialUrl: "https://www.suomi.fi/guides/preparedness",
      additionalUrls: [
        { label: "FMI CAP warnings", href: "https://alerts.fmi.fi/cap/profile/current/" },
      ],
      systems: nationalWarningSystems.countries.FI,
    },
    {
      group: "National warnings",
      name: "France (FR) warning systems",
      role: "Official national and direct warning sources reviewed for France.",
      availability: "National civil-alert partition enabled; 1 active, 1 gated systems listed.",
      details: "FR-Alert (active; national warning feed); Météo-France Vigilance API (credential-gated; official link/review only).",
      officialUrl: "https://fr-alert.gouv.fr/les-alertes",
      additionalUrls: [
        { label: "Météo-France Vigilance API", href: "https://www.data.gouv.fr/dataservices/api-bulletin-vigilance" },
      ],
      systems: nationalWarningSystems.countries.FR,
    },
    {
      group: "National warnings",
      name: "United Kingdom (GB) warning systems",
      role: "Official national and direct warning sources reviewed for United Kingdom.",
      availability: "National civil-alert partition enabled; 1 active, 5 gated systems listed.",
      details: "England flood warnings (active; national warning feed); MeteoAlarm keyless Atom warning feed (evidence-gated; official link/review only); MeteoAlarm authenticated EDR recovery (evidence-gated; official link/review only); Met Office UK weather warnings (evidence-gated; official link/review only); National Severe Weather Warning Service (credential-gated; national warning feed); Wales flood warnings (credential-gated; national warning feed).",
      officialUrl: "https://check-for-flooding.service.gov.uk/",
      additionalUrls: [
        { label: "MeteoAlarm keyless Atom warning feed", href: "https://www.meteoalarm.org/" },
        { label: "Met Office UK weather warnings", href: "https://weather.metoffice.gov.uk/warnings-and-advice/uk-warnings" },
        { label: "National Severe Weather Warning Service", href: "https://www.metoffice.gov.uk/weather/warnings-and-advice/uk-warnings" },
        { label: "Wales flood warnings", href: "https://naturalresources.wales/flooding/check-flood-warnings/?lang=en" },
      ],
      systems: nationalWarningSystems.countries.GB,
    },
    {
      group: "National warnings",
      name: "Greece (GR) warning systems",
      role: "Official national and direct warning sources reviewed for Greece.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "112 Greece (evidence-gated; official link/review only).",
      officialUrl: "https://civilprotection.gov.gr/",
      systems: nationalWarningSystems.countries.GR,
    },
    {
      group: "National warnings",
      name: "Croatia (HR) warning systems",
      role: "Official national and direct warning sources reviewed for Croatia.",
      availability: "National civil-alert partition not enabled; 1 active, 1 blocked systems listed.",
      details: "SRUUK (blocked; official link/review only); DHMZ direct CAP warnings (active; MeteoAlarm fallback).",
      officialUrl: "https://civilna-zastita.gov.hr/",
      additionalUrls: [
        { label: "DHMZ direct CAP warnings", href: "https://meteo.hr/proizvodi.php?section=podaci&param=xml_korisnici" },
      ],
      systems: nationalWarningSystems.countries.HR,
    },
    {
      group: "National warnings",
      name: "Hungary (HU) warning systems",
      role: "Official national and direct warning sources reviewed for Hungary.",
      availability: "National civil-alert partition not enabled; 1 blocked system listed.",
      details: "VÉSZ (blocked; official link/review only).",
      officialUrl: "https://www.katasztrofavedelem.hu/",
      systems: nationalWarningSystems.countries.HU,
    },
    {
      group: "National warnings",
      name: "Ireland (IE) warning systems",
      role: "Official national and direct warning sources reviewed for Ireland.",
      availability: "National civil-alert partition not enabled; 1 active, 1 blocked systems listed.",
      details: "Ireland public warning system (blocked; official link/review only); Met Eireann warnings (active; MeteoAlarm fallback).",
      officialUrl: "https://www.gov.ie/en/department-of-defence/organisation-information/office-of-emergency-planning/",
      additionalUrls: [
        { label: "Met Eireann warnings", href: "https://www.met.ie/warnings-today.html" },
      ],
      systems: nationalWarningSystems.countries.IE,
    },
    {
      group: "National warnings",
      name: "Iceland (IS) warning systems",
      role: "Official national and direct warning sources reviewed for Iceland.",
      availability: "National civil-alert partition not enabled; 1 active, 2 gated systems listed.",
      details: "MeteoAlarm keyless Atom warning feed (active; MeteoAlarm primary); MeteoAlarm authenticated EDR recovery (credential-gated; MeteoAlarm fallback); Icelandic Met Office (evidence-gated; official link/review only).",
      officialUrl: "https://www.meteoalarm.org/",
      additionalUrls: [
        { label: "Icelandic Met Office", href: "https://en.vedur.is/" },
      ],
      systems: nationalWarningSystems.countries.IS,
    },
    {
      group: "National warnings",
      name: "Italy (IT) warning systems",
      role: "Official national and direct warning sources reviewed for Italy.",
      availability: "National civil-alert partition enabled; 1 active, 1 gated, 1 blocked systems listed.",
      details: "IT-alert (blocked; official link/review only); National hydrogeological and hydraulic bulletin (active; national warning feed); Italian volcanic warnings and restrictions (evidence-gated; official link/review only).",
      officialUrl: "https://www.it-alert.gov.it/en/",
      additionalUrls: [
        { label: "National hydrogeological and hydraulic bulletin", href: "https://mappe.protezionecivile.gov.it/it/mappe-rischi/bollettino-di-criticita/" },
        { label: "Italian volcanic warnings and restrictions", href: "https://rischi.protezionecivile.gov.it/it/vulcanico/vulcani-italia/stromboli/" },
      ],
      systems: nationalWarningSystems.countries.IT,
    },
    {
      group: "National warnings",
      name: "Liechtenstein (LI) warning systems",
      role: "Official national and direct warning sources reviewed for Liechtenstein.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "Liechtenstein government information (evidence-gated; official link/review only).",
      officialUrl: "https://www.llv.li/",
      systems: nationalWarningSystems.countries.LI,
    },
    {
      group: "National warnings",
      name: "Lithuania (LT) warning systems",
      role: "Official national and direct warning sources reviewed for Lithuania.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "LT72 (evidence-gated; official link/review only).",
      officialUrl: "https://lt72.lt/",
      systems: nationalWarningSystems.countries.LT,
    },
    {
      group: "National warnings",
      name: "Luxembourg (LU) warning systems",
      role: "Official national and direct warning sources reviewed for Luxembourg.",
      availability: "National civil-alert partition enabled; 1 active system listed.",
      details: "LU-Alert (active; national warning feed).",
      officialUrl: "https://data.public.lu/fr/datasets/alertes-du-systeme-lu-alert/",
      systems: nationalWarningSystems.countries.LU,
    },
    {
      group: "National warnings",
      name: "Latvia (LV) warning systems",
      role: "Official national and direct warning sources reviewed for Latvia.",
      availability: "National civil-alert partition enabled; 1 active, 1 gated systems listed.",
      details: "Latvia public warning system (evidence-gated; official link/review only); LVĢMC hydrological warnings (active; national warning feed).",
      officialUrl: "https://www.vugd.gov.lv/en",
      additionalUrls: [
        { label: "LVĢMC hydrological warnings", href: "https://data.gov.lv/dati/dataset/hidrometeorologiskie-bridinajumi" },
      ],
      systems: nationalWarningSystems.countries.LV,
    },
    {
      group: "National warnings",
      name: "Monaco (MC) warning systems",
      role: "Official national and direct warning sources reviewed for Monaco.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "Monaco government information (evidence-gated; official link/review only).",
      officialUrl: "https://www.gouv.mc/",
      systems: nationalWarningSystems.countries.MC,
    },
    {
      group: "National warnings",
      name: "Moldova (MD) warning systems",
      role: "Official national and direct warning sources reviewed for Moldova.",
      availability: "National civil-alert partition not enabled; 3 gated systems listed.",
      details: "MeteoAlarm keyless Atom warning feed (evidence-gated; official link/review only); MeteoAlarm authenticated EDR recovery (evidence-gated; official link/review only); Moldova weather warnings (evidence-gated; official link/review only).",
      officialUrl: "https://www.meteoalarm.org/",
      additionalUrls: [
        { label: "Moldova weather warnings", href: "https://www.meteo.md/index.php/ro/weather/current-warnings/" },
      ],
      systems: nationalWarningSystems.countries.MD,
    },
    {
      group: "National warnings",
      name: "Montenegro (ME) warning systems",
      role: "Official national and direct warning sources reviewed for Montenegro.",
      availability: "National civil-alert partition not enabled; 3 gated systems listed.",
      details: "MeteoAlarm keyless Atom warning feed (evidence-gated; official link/review only); MeteoAlarm authenticated EDR recovery (evidence-gated; official link/review only); Montenegro Hydrometeorological and Seismological Service (evidence-gated; official link/review only).",
      officialUrl: "https://www.meteoalarm.org/",
      additionalUrls: [
        { label: "Montenegro Hydrometeorological and Seismological Service", href: "https://www.meteo.co.me/" },
      ],
      systems: nationalWarningSystems.countries.ME,
    },
    {
      group: "National warnings",
      name: "North Macedonia (MK) warning systems",
      role: "Official national and direct warning sources reviewed for North Macedonia.",
      availability: "National civil-alert partition not enabled; 3 gated systems listed.",
      details: "MeteoAlarm keyless Atom warning feed (evidence-gated; official link/review only); MeteoAlarm authenticated EDR recovery (evidence-gated; official link/review only); North Macedonia Hydrometeorological Service (evidence-gated; official link/review only).",
      officialUrl: "https://www.meteoalarm.org/",
      additionalUrls: [
        { label: "North Macedonia Hydrometeorological Service", href: "https://uhmr.gov.mk/" },
      ],
      systems: nationalWarningSystems.countries.MK,
    },
    {
      group: "National warnings",
      name: "Malta (MT) warning systems",
      role: "Official national and direct warning sources reviewed for Malta.",
      availability: "National civil-alert partition not enabled; 1 blocked system listed.",
      details: "Malta public warning system (blocked; official link/review only).",
      officialUrl: "https://cps.gov.mt/",
      systems: nationalWarningSystems.countries.MT,
    },
    {
      group: "National warnings",
      name: "Netherlands (NL) warning systems",
      role: "Official national and direct warning sources reviewed for Netherlands.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "NL-Alert (evidence-gated; official link/review only).",
      officialUrl: "https://www.nl-alert.nl/",
      systems: nationalWarningSystems.countries.NL,
    },
    {
      group: "National warnings",
      name: "Norway (NO) warning systems",
      role: "Official national and direct warning sources reviewed for Norway.",
      availability: "National civil-alert partition enabled; 2 active, 3 gated systems listed.",
      details: "MET Norway MetAlerts (active; national warning feed); NVE flood warnings (active; national warning feed); MeteoAlarm keyless Atom warning feed (evidence-gated; official link/review only); MeteoAlarm authenticated EDR recovery (evidence-gated; official link/review only); Varsom natural hazard warnings (evidence-gated; official link/review only).",
      officialUrl: "https://www.met.no/en/weather-and-climate/text-forecast-and-warnings",
      additionalUrls: [
        { label: "NVE flood warnings", href: "https://www.varsom.no/en/flood-and-landslide-warning-service/" },
        { label: "MeteoAlarm keyless Atom warning feed", href: "https://www.meteoalarm.org/" },
        { label: "Varsom natural hazard warnings", href: "https://www.varsom.no/en/" },
      ],
      systems: nationalWarningSystems.countries.NO,
    },
    {
      group: "National warnings",
      name: "Poland (PL) warning systems",
      role: "Official national and direct warning sources reviewed for Poland.",
      availability: "National civil-alert partition enabled; 1 active system listed.",
      details: "IMGW hydrology warnings (active; national warning feed).",
      officialUrl: "https://hydro.imgw.pl/",
      systems: nationalWarningSystems.countries.PL,
    },
    {
      group: "National warnings",
      name: "Portugal (PT) warning systems",
      role: "Official national and direct warning sources reviewed for Portugal.",
      availability: "National civil-alert partition not enabled; 1 active, 2 gated, 1 blocked systems listed.",
      details: "IPMA weather warnings (active; MeteoAlarm fallback); PROCIV (blocked; official link/review only); Azores Civil Protection alerts (evidence-gated; national warning feed); ANEPC operational incidents (evidence-gated; national warning feed).",
      officialUrl: "https://www.ipma.pt/en/otempo/prev-sam/",
      additionalUrls: [
        { label: "PROCIV", href: "https://prociv.gov.pt/" },
        { label: "Azores Civil Protection alerts", href: "https://www.prociv.azores.gov.pt/alertas/" },
        { label: "ANEPC operational incidents", href: "https://prociv.gov.pt/pt/ocorrencias/" },
      ],
      systems: nationalWarningSystems.countries.PT,
    },
    {
      group: "National warnings",
      name: "Romania (RO) warning systems",
      role: "Official national and direct warning sources reviewed for Romania.",
      availability: "National civil-alert partition not enabled; 1 blocked system listed.",
      details: "RO-ALERT (blocked; official link/review only).",
      officialUrl: "https://www.mai.gov.ro/",
      systems: nationalWarningSystems.countries.RO,
    },
    {
      group: "National warnings",
      name: "Serbia (RS) warning systems",
      role: "Official national and direct warning sources reviewed for Serbia.",
      availability: "National civil-alert partition not enabled; 3 gated systems listed.",
      details: "MeteoAlarm keyless Atom warning feed (evidence-gated; official link/review only); MeteoAlarm authenticated EDR recovery (evidence-gated; official link/review only); Serbia hydrometeorological warnings (evidence-gated; official link/review only).",
      officialUrl: "https://www.meteoalarm.org/",
      additionalUrls: [
        { label: "Serbia hydrometeorological warnings", href: "https://www.hidmet.gov.rs/latin/upozorenja/index.php" },
      ],
      systems: nationalWarningSystems.countries.RS,
    },
    {
      group: "National warnings",
      name: "Sweden (SE) warning systems",
      role: "Official national and direct warning sources reviewed for Sweden.",
      availability: "National civil-alert partition enabled; 1 active, 1 gated systems listed.",
      details: "Krisinformation (active; national warning feed); SMHI direct warnings (evidence-gated; official link/review only).",
      officialUrl: "https://www.krisinformation.se/en",
      additionalUrls: [
        { label: "SMHI direct warnings", href: "https://opendata-download-warnings.smhi.se/ibww/api/version/1" },
      ],
      systems: nationalWarningSystems.countries.SE,
    },
    {
      group: "National warnings",
      name: "Slovenia (SI) warning systems",
      role: "Official national and direct warning sources reviewed for Slovenia.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "Slovenia public warning system (evidence-gated; official link/review only).",
      officialUrl: "https://www.gov.si/en/state-authorities/bodies-within-ministries/administration-for-civil-protection-and-disaster-relief/",
      systems: nationalWarningSystems.countries.SI,
    },
    {
      group: "National warnings",
      name: "Slovakia (SK) warning systems",
      role: "Official national and direct warning sources reviewed for Slovakia.",
      availability: "National civil-alert partition not enabled; 1 gated, 1 blocked systems listed.",
      details: "Slovakia public warning system (blocked; official link/review only); Crisis-management REST service (credential-gated; national warning feed).",
      officialUrl: "https://www.minv.sk/",
      additionalUrls: [
        { label: "Crisis-management REST service", href: "https://portal.minv.sk/wps/esispz-api/docs/index.html" },
      ],
      systems: nationalWarningSystems.countries.SK,
    },
    {
      group: "National warnings",
      name: "San Marino (SM) warning systems",
      role: "Official national and direct warning sources reviewed for San Marino.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "San Marino civil protection orders (evidence-gated; official link/review only).",
      officialUrl: "https://www.gov.sm/pub1/GovSM/Circolari-e-Ordinanze/Ordinanze-Protezione-Civile.html",
      systems: nationalWarningSystems.countries.SM,
    },
    {
      group: "National warnings",
      name: "Türkiye (TR) warning systems",
      role: "Official national and direct warning sources reviewed for Türkiye.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "Türkiye meteorological information (evidence-gated; official link/review only).",
      officialUrl: "https://www.mgm.gov.tr/",
      systems: nationalWarningSystems.countries.TR,
    },
    {
      group: "National warnings",
      name: "Vatican City (VA) warning systems",
      role: "Official national and direct warning sources reviewed for Vatican City.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "Vatican City State information (evidence-gated; official link/review only).",
      officialUrl: "https://www.vaticanstate.va/en/",
      systems: nationalWarningSystems.countries.VA,
    },
    {
      group: "National warnings",
      name: "Kosovo (XK) warning systems",
      role: "Official national and direct warning sources reviewed for Kosovo.",
      availability: "National civil-alert partition not enabled; 1 gated system listed.",
      details: "Kosovo Hydrometeorological Institute (evidence-gated; official link/review only).",
      officialUrl: "https://ihmk-rks.net/",
      systems: nationalWarningSystems.countries.XK,
    },
  ],
} as const;
